/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f7682daf-7aae-4f98-9b26-9221b6a27cbf",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_bQXnM6KSr",
    "aws_user_pools_web_client_id": "6h2nlidglk2n9r7sodj9bchbk4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://vm4zn7kh4vgcjn3m3rpxu3fuha.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "plaidhandler",
            "endpoint": "https://3wsvb7voz8.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        },
        {
            "name": "transaction2service",
            "endpoint": "https://jffcxbr3yi.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
